apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-demo-blue
  namespace: default
  labels:
    app: rolling-update-strategy
spec:
  selector:
    matchLabels:
      app: rolling-update-strategy
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rolling-update-strategy
    spec:
      containers:
      - name: rolling-update-container
        image: adamtravis/rollouts:blue
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rolling-update-type-service
  labels:
    app: rolling-update-strategy
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31000
  selector:
    app: rolling-update-strategy
  type: NodePort
